language: java

# Cache the .m2 folder to prevent redownloading dependencies on each build
cache:
  directories:
  - "$HOME/.m2/repository"

jdk: oraclejdk8

# Environment variables are strings (double quotes)
# Example:
# - secure: "DpR1th9rZvLMX0......"
env:
  global:
    - secure: "hxpS1jR0JcL+Iz4b8mj5v+SMLwlnTc/HwKEH0J7CBpgRlTjJ2CpUnI1W3tvghIscBy5QZT7YutuwtD5kwJoTmod5t48er8ICpCrzCEcurQ0sqg1OFXisXi+74+8UcLfLGo8UKeZv96lZH6NiBcvErf0hMVL0vCokZPxceRmuwnaOXdcJbu+u+OfqywuTZ1BSgd/zzmeeYALJ+L0am9D86CBAoFJDMxu0VEGSkRpdyQizOfd1LGG2beJtkevHCiYEDoCvfAj0jmR+6d9CJRzBJ+oY9JhjDs8v7Ufi2csi0BNIBAmcjCeeHcatOGk+keLgj1TP8637yZi7CqDtTI5PPohW2zCm1P9+a8dFvyVKJPi6EN6G6475T+JJelA5VYYMDQzqMzhTs35djrbaa6V7AtQyp00JYHdtZH5TXrxLcqftpo3+44D1Sk8r6UAykOYux50QRDz4mxcKiHWtN5yuhxirwmPi/4JSSWoNC5aIkXIG3hv7jmd71trqVROzbB399jayvfx0B+yvmzb4b/yDGmNBmWrmAOruwA9bazkGL2ZS47Ggtdde8BsbYD86HMBSP1LJ2r4moBBTg7ofTxop9rjI7hct5deh/xUkir0RwQZcYviWBggOVGTv7RSs42wW6lPmmQk9WEW/XJBOLmdWGKCmGy/sJMufaKrPnJEmSqM="

    - secure: "gKi7k2M0NQOT7Im04PnPz74t9g69Z5pEKkQCoLNpWKoIjF66eqUQ1Yu5lvZUofob8gbGHAYUfq1JFj2hNLvdEwhpyPyB2HpSYea51FrrH7VYi8IRNMLMkn6yXM/PjBhlpUZtSFGRP8ibJRV3GT2T4gNBfPOB6sqTaThAWGGnjmdhfDDeNf+NGO0ic4HueHUvi9SDParH9nxehDJRbTIfbpWuKDWgweGFFhVmD26Q/bPyuv4Qky9YcxBxHCnOIByLOgNequ1XG+CRnyU18MqMcN1DQ6WUnUXpwcSeoJHychOrsZLJ386cZRLrABXtyF4AiIl8cOTyqsTa2S0Ma/pIf+Q/j1tr+67qPFnabddDXv5WpyXlnLdZz0xrwFr4GtUS4nJzWtYtT8P9flEqvpX+HWxUpkNAIJOxII6TLxE1q04q3zCm9T9lY1ZmxjiJ2bwJTVwXr7u2tgTudAi7BTWIAhtrHT8PZ220n8K+2tmoSW8djewfFFvMQDG3iGWkdd46ppz7mXF2/DTVmZ8jm8e6BCugx/zLVA7nrk6LLhGS/jNWCdhtprwAhxgmNeXvpy9bJeyIWaUknuXkyBmh8KLTP97ZVl8e2B7wwR5D93nI8skzYlT0Dnd6p6DIDvB0zPNrzsv78JWNil5PvfWE1k45IEBQDadHQLWBX8ROmR/YkQk="

# Define the services to use
services:
  - docker

before_install:
...
# Prepare deploy
  - openssl aes-256-cbc -K $encrypted_xxxxxxx_key -iv $encrypted_xxxxxxxxxxx_iv
    -in travis_deploy_rsa.enc -out ~\/.ssh/travis_deploy_rsa -d  # Généré par travis encrypt-file
  - chmod 600 /tmp/travis_deploy_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add /tmp/travis_deploy_rsa
  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

...

# Deploy updated container over ssh
deploy:
  provider: script
  script: ssh -i /tmp/travis_deploy_rsa $DEPLOY_USER@$SERVER_HOST "sudo docker pull $IMAGE_NAME:$TAG && sudo docker rm -f app || true && sudo docker run -d --network net -p 80:8080 --name app $IMAGE_NAME:$TAG"
  on:
    branch: master
