language: java

# Cache the .m2 folder to prevent redownloading dependencies on each build
cache:
  directories:
  - "$HOME/.m2/repository"

jdk: oraclejdk8

# Environment variables are strings (double quotes)
# Example:
# - secure: "DpR1th9rZvLMX0......"
env:
  global:
    - secure: "WBiYsJ4xSnx8DrMsIFBG5+kH8M8uwouK5X2Ci8omSZt1PPINHfG069dt4WW8gabLNEmeRwcrdmgUWmvVNcrGlkXgbH5WuKXAztuINQixnBZ6jOuaMH4U0edYwrEc/uqnI0MKBOn4DS2ee5QXZXuOf9bED+4fV7m62nagvtpExvJBAWjlfXPzyrntH98Cixw1e65SN6t6yFDt/bhfQVqIFKjCBGkLAVtqyrWNJ8jreXSgRH86nLA6jVA1R2ilKAu8HxWw7AVpwTiP6fdViGMzwTgMG86MoMrQiylnvsQrdoFh5bzxHtPjCDdK1ZOpXByCLglnoKlcYE7e1Cz+wiULZCUSaQPEfkYPQ5UGFvbJ61wVH2GgPj0OGe8eTHu1sG0sa6Cx4pGtH8gOT6fOOB1YoSybA1eR9iZIq1guI5pZ0p7N4qiRkprxoV3kpmQ4RccFYXRS1uuPw+U+q983WgKPkKORX4mIuKE+WlaI4SYYDI74Iq+gD9U6pCxzHi1w1AUTrItP9pElgVm5F9ZlSJ4NnCKsxzEjUqXiIV463PMr5BBvGTR6jb3M8ayskhMM+B3V9yTcKGShz8LvUI2Kq9t2MHxeYJC16UtL5YOWYrzmBzw7PJVLcWJ29391I3dEQ4LIU8qmC/tlJ03LwSfXkQgNJoiij9Q+ZWxnSifjAIbghyM="


# Define the services to use
services:
  - docker

before_install:
  - sudo service mysql stop
  - docker pull takimatraining/devops-training-db
  - docker run -d -p 127.0.0.1:3306:3306 takimatraining/devops-training-db




#script:
#  - mvn verify


# The pipe (|) is useful to create multiline scripts
script:
  - |
    mvn clean install sonar:sonar \
    -Dsonar.projectKey=Gabriel382_sample-application-students\
    -Dsonar.organization=gabriel382-github \
    -Dsonar.host.url=https://sonarcloud.io \
    -Dsonar.login=a2b031fb4c4a36af2141d833e90615ed71ee98a6


